const express = require('express');
const router = express.Router();
const { getEmployees, getEmployeeById, updateEmployee } = require('../controllers/employeeController');
const { requireAuth } = require('../middleware/auth');
router.use(requireAuth);
router.get('/', getEmployees);
router.get('/:id', getEmployeeById);
router.put('/:id', updateEmployee);
router.patch('/:id', updateEmployee);
module.exports = router;
